### ISSUE TITLE
Task tracking

### ISSUE THREAD

**Issue by Thierry-Kq** [Nouvelle-Techno-fr/JeBenevole.fr#31]
**Week 1** 

- [x] [Entities](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/23) ( Nox ) 
- [x] [Fixtures](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/24) ( Nox ) 
- [x] [Translations](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/25) ( Kass )
- [ ] [CRUD User](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/26) ( Anass ) 
- [x] [CRUD Association](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/27) ( Renaissance ) 

**Week 2** 
- [x] [4xx 5xx](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/32) ( Renaissance ) 
- [ ] [CRUD Offer](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/28) ( Kass ) 
- [ ] [CRUD Categories](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/49) ( Renaissance ) 
- [ ] [Frontend components (navbar / footer) ](https://github.com/Nouvelle-Techno-fr/JeBenevole.fr/issues/34) ( Nox )
